#!/bin/sh
# $MirOS: src/scripts/cleanenv,v 1.6 2021/02/07 02:07:58 tg Exp $

p=/bin:/usr/bin:/sbin:/usr/sbin:/usr/X11R6/bin

a1=$1

if test x"$a1" = x"/"; then
	cd /
	a1=-
fi

if test x"$a1" = x"-"; then
	shift
	exec /usr/bin/env -i \
	    PATH=$p HOME=/ LC_ALL=C.UTF-8 \
	    "$@"
fi

exec /usr/bin/env -i \
    PATH=$p TZ=UTC $(locale 2>/dev/null | fgrep LC_CTYPE) \
    DISPLAY="$DISPLAY" HOME="${HOME:-/}" TERM="${TERM:-vt100}" USER="${USER}" \
    "$@"
