#!/bin/mksh
#-
# Copyright © 2015, 2018
#	mirabilos <m@mirbsd.org>
#
# Provided that these terms and disclaimer and all copyright notices
# are retained or reproduced in an accompanying document, permission
# is granted to deal in this work without restriction, including un‐
# limited rights to use, publicly perform, distribute, sell, modify,
# merge, give away, or sublicence.
#
# This work is provided “AS IS” and WITHOUT WARRANTY of any kind, to
# the utmost extent permitted by applicable law, neither express nor
# implied; without malicious intent or gross negligence. In no event
# may a licensor, author or contributor be held liable for indirect,
# direct, other damage, loss, or other issues arising in any way out
# of dealing in the work, even if advised of the possibility of such
# damage or existence of a defect, except proven that it results out
# of said person’s immediate fault when using the work as intended.

ulimit -c 0

local _i _fm=$2 _h=$1
shift; shift

[[ $_fm = *'*' ]] || _fm=${_fm@Q}

trap "" INT
ssh "$_h" find "$_fm" -follow -type f -print0 | sort -R "" | \
    while IFS= read -r -d "" _i; do
	print -r "◖${_i}◗"
	ssh -n "$_h" cat "${_i@Q}" | "$@"
done
