#!/bin/mksh
# $MirOS: contrib/hosted/tg/dumpargs,v 1.2 2013/05/18 15:34:34 tg Exp $
#-
# Copyright © 2013
#	Thorsten Glaser <tg@mirbsd.org>
#
# Provided that these terms and disclaimer and all copyright notices
# are retained or reproduced in an accompanying document, permission
# is granted to deal in this work without restriction, including un‐
# limited rights to use, publicly perform, distribute, sell, modify,
# merge, give away, or sublicence.
#
# This work is provided “AS IS” and WITHOUT WARRANTY of any kind, to
# the utmost extent permitted by applicable law, neither express nor
# implied; without malicious intent or gross negligence. In no event
# may a licensor, author or contributor be held liable for indirect,
# direct, other damage, loss, or other issues arising in any way out
# of dealing in the work, even if advised of the possibility of such
# damage or existence of a defect, except proven that it results out
# of said person’s immediate fault when using the work as intended.
#-
# Dump process environment to syslog.

{
	{
		typeset -p
		print -n "args($#)"
		i=-1
		for x in "$0" "$@"; do
			print -nr -- " $((++i)):${x@Q}"
		done
		print
	} | /usr/bin/tee /dev/stderr | \
	    /usr/bin/logger -p user.debug -t "dumpargs[$$]"
} 2>&1 | {
	print "=== dumpargs[$$] ==="
	cat
}
