#!/bin/mksh
# -*- mode: sh -*-
#-
# Copyright © 2022
#	mirabilos <m@mirbsd.org>
#
# Provided that these terms and disclaimer and all copyright notices
# are retained or reproduced in an accompanying document, permission
# is granted to deal in this work without restriction, including un‐
# limited rights to use, publicly perform, distribute, sell, modify,
# merge, give away, or sublicence.
#
# This work is provided “AS IS” and WITHOUT WARRANTY of any kind, to
# the utmost extent permitted by applicable law, neither express nor
# implied; without malicious intent or gross negligence. In no event
# may a licensor, author or contributor be held liable for indirect,
# direct, other damage, loss, or other issues arising in any way out
# of dealing in the work, even if advised of the possibility of such
# damage or existence of a defect, except proven that it results out
# of said person’s immediate fault when using the work as intended.
#-
# Calculates the earth’s cross-quarter days via the JPL Horizons API
# and the quarter days using the golden ratio approach documented by
# http://web.archive.org/web/20170628085124/http://www.astrothek.de/artikel/jahreskreis/jahreskreis_termine.html
#
# The service http://aa.usno.navy.mil/data/docs/EarthSeasons.php had
# (though at less precision) the former but was discontinued.
#
# Output is in BSD calendar(1) format.

unset LANGUAGE
export LC_ALL=C POSIXLY_CORRECT=1
set -ex
: upgrade your mksh should this fail:
set -o noglob -o pipefail +x

