#!/bin/mksh
# $MirOS: contrib/hosted/tg/fccombine,v 1.1 2013/11/23 14:20:53 tg Exp $
#-
# Copyright © 2013
#	Thorsten Glaser <tg@mirbsd.org>
#
# Provided that these terms and disclaimer and all copyright notices
# are retained or reproduced in an accompanying document, permission
# is granted to deal in this work without restriction, including un‐
# limited rights to use, publicly perform, distribute, sell, modify,
# merge, give away, or sublicence.
#
# This work is provided “AS IS” and WITHOUT WARRANTY of any kind, to
# the utmost extent permitted by applicable law, neither express nor
# implied; without malicious intent or gross negligence. In no event
# may a licensor, author or contributor be held liable for indirect,
# direct, other damage, loss, or other issues arising in any way out
# of dealing in the work, even if advised of the possibility of such
# damage or existence of a defect, except proven that it results out
# of said person’s immediate fault when using the work as intended.
#-
# Combine files on their first column. Example:
#	<wsp*>foo<wsp+>bar<wsp*><nl>
#	<wsp*>foo<wsp+>baz<wsp*><nl>
#	<wsp*>bla<wsp+>moo<wsp*><nl>
# will become:
#	foo<tab>bar<tab>baz<nl>
#	bla<tab>moo<nl>
# A line with no second column will also skip the tab. An empty line
# will separate output but be otherwise ignored.

IFS=$' \t\n\r\f\v'
last=
while read -r first rest; do
	if [[ $first != "$last" ]]; then
		[[ -n $last ]] && print
		last=$first
		print -nr -- "$first"
	fi
	[[ -n $rest ]] && print -nr -- $'\t'"$rest"
done
[[ -n $last ]] && print
