#!/bin/mksh
# $MirOS: contrib/hosted/tg/flacplay,v 1.2 2012/09/29 14:07:15 tg Exp $

if a=$(whence -p waveplay) && [[ -n $a && -x $a ]]; then
	alias _wavplay='waveplay -'
else
	alias _wavplay='sox -t wav /dev/stdin -t sunau /dev/audio'
fi

trap "" INT

for a in "$@"; do
	if [[ $a = - || -s $a ]]; then
		[[ $a = - ]] || print -ru2 "♬ $a"
		flac -d -c "$a" | _wavplay
	else
		print -ru2 "Skipping illegible '$a'"
	fi
done
