#!/bin/mksh
# -*- mode: sh -*-
#-
# Copyright © 2014, 2015
#	mirabilos <m$(date +%Y)@mirbsd.de>
#
# Provided that these terms and disclaimer and all copyright notices
# are retained or reproduced in an accompanying document, permission
# is granted to deal in this work without restriction, including un‐
# limited rights to use, publicly perform, distribute, sell, modify,
# merge, give away, or sublicence.
#
# This work is provided “AS IS” and WITHOUT WARRANTY of any kind, to
# the utmost extent permitted by applicable law, neither express nor
# implied; without malicious intent or gross negligence. In no event
# may a licensor, author or contributor be held liable for indirect,
# direct, other damage, loss, or other issues arising in any way out
# of dealing in the work, even if advised of the possibility of such
# damage or existence of a defect, except proven that it results out
# of said person’s immediate fault when using the work as intended.

function die {
	print -r -- E: "$@"
	exit 1
}

cr=$'\r'
nl=$'\n'
s=
st=0
while IFS= read -r line; do
	case $st,${line%"$cr"} {
	(0,*-----BEGIN\ PGP\ MESSAGE-----)
		p=${line%-----BEGIN\ PGP\ MESSAGE-----?("$cr")}
		c=${line#"$p"}$nl
		cs=
		st=1
		;;
	(0,*)
		s+=$line$nl
		;;
	(1,"$p"-----END\ PGP\ MESSAGE-----)
		die pgp message invalid
		;;
	(1,"$p"?(\ ))
		# switch from header to body; Enigmail bogusly adds a space
		st=2
		;|
	(2,"$p"-----END\ PGP\ MESSAGE-----)
		c+=${line#"$p"}
		c=$(print -r -- "$c" | gpg1 "$@") || die gpg failed
		x=
		[[ -z $cs ]] || if x=$(print -r -- "$c" | \
		    iconv -f "$cs" -t utf-8); then
			c=$x
			x=
		else
			x="‣‣‣ WARNING: iconv from ${cs@Q} failed!$nl$nl"
		fi
		c=$nl$c
		c=${c//"$nl"/"$nl$p"}
		s+=$x${c#"$nl"}$nl
		st=0
		;;
	(1,"$p"Charset:*)
		cs=${line#"$p"Charset:}
		cs=${cs##+([	 ])}
		cs=${cs%%+([	 ])}
		;&
	([12],"$p"*)
		c+=${line#"$p"}$nl
		;;
	([12],*)
		die pgp message not indented consistently
		;;
	}
done
print -nr -- "$s"
exit 0
