#!/bin/mksh
# $Id: ldapshow 2260 2011-08-25 13:05:53Z tglase $
#-
# Copyright © 2011
#	Thorsten Glaser <t.glaser@tarent.de>
#
# Provided that these terms and disclaimer and all copyright notices
# are retained or reproduced in an accompanying document, permission
# is granted to deal in this work without restriction, including un‐
# limited rights to use, publicly perform, distribute, sell, modify,
# merge, give away, or sublicence.
#
# This work is provided “AS IS” and WITHOUT WARRANTY of any kind, to
# the utmost extent permitted by applicable law, neither express nor
# implied; without malicious intent or gross negligence. In no event
# may a licensor, author or contributor be held liable for indirect,
# direct, other damage, loss, or other issues arising in any way out
# of dealing in the work, even if advised of the possibility of such
# damage or existence of a defect, except proven that it results out
# of said person’s immediate fault when using the work as intended.
#-
# Call ldapsearch, output onelined, empty line after every block

# check for new enough mksh version
set -A PIPESTATUS -- 23 42
false | true | true
set -A rv -- "${PIPESTATUS[@]}"
if [[ ${#rv[*]} != 3 || ${rv[0]} != 1 || ${rv[1]} != 0 || ${rv[2]} != 0 ]]; then
	print -u2 need mksh R40
	exit 255
fi

ldapsearch -xLLL "$@" | tr '\n' $'\a' | sed -e $'s/\a //g' | tr $'\a' '\n'
set -A rv -- "${PIPESTATUS[@]}"
exit ${rv[0]}
