#!/bin/mksh
#-
# Copyright © 2016
#	mirabilos <m@mirbsd.org>
#
# Provided that these terms and disclaimer and all copyright notices
# are retained or reproduced in an accompanying document, permission
# is granted to deal in this work without restriction, including un‐
# limited rights to use, publicly perform, distribute, sell, modify,
# merge, give away, or sublicence.
#
# This work is provided “AS IS” and WITHOUT WARRANTY of any kind, to
# the utmost extent permitted by applicable law, neither express nor
# implied; without malicious intent or gross negligence. In no event
# may a licensor, author or contributor be held liable for indirect,
# direct, other damage, loss, or other issues arising in any way out
# of dealing in the work, even if advised of the possibility of such
# damage or existence of a defect, except proven that it results out
# of said person’s immediate fault when using the work as intended.

[[ -n $1 ]] && IFS=$1

l1=
l2=
lp=0
while read -r n1 n2; do
	if [[ $n1 = $l1 ]]; then
		l2+=$IFS$n2
		lp=1
		continue
	fi
	if (( lp )); then
		print -r -- "$l1$IFS$l2"
		lp=0
	fi
	l1=$n1
	l2=$n2
done
(( lp )) && print -r -- "$l1$IFS$l2"
