#!/bin/mksh
# $MirOS: contrib/hosted/tg/rcp,v 1.7 2024/11/06 11:34:49 tg Exp $
#-
# Copyright (c) 2009, 2010, 2013, 2020, 2024
#	mirabilos <m@mirbsd.org>
#
# Provided that these terms and disclaimer and all copyright notices
# are retained or reproduced in an accompanying document, permission
# is granted to deal in this work without restriction, including un-
# limited rights to use, publicly perform, distribute, sell, modify,
# merge, give away, or sublicence.
#
# This work is provided "AS IS" and WITHOUT WARRANTY of any kind, to
# the utmost extent permitted by applicable law, neither express nor
# implied; without malicious intent or gross negligence. In no event
# may a licensor, author or contributor be held liable for indirect,
# direct, other damage, loss, or other issues arising in any way out
# of dealing in the work, even if advised of the possibility of such
# damage or existence of a defect, except proven that it results out
# of said person's immediate fault when using the work as intended.

sshx="--rsh=ssh -T"
set -A args -- "$@"
a=a
i=0
is_inplace=0
numeric_ids=--numeric-ids
while (( i < ${#args[*]} )); do
	case ${args[i]} {
	(-4)
		sshx="$sshx -4"
		unset args[i]
		;;
	(-a)
		# -a replacement for FAT filesystem targets
		a=rlDc
		unset args[i]
		;;
	(--all)
		# -a for Linux extattrs etc.
		a=aAX
		#a=aAXUNH (-U/-N are atime/birthtime, -N already below)
		unset args[i]
		;;
	(-h)
		print -u2 "Syntax:\t$0 [-h] [-4] [--sshkey=~/.etc/ssh/id_rsa] \\"
		print -u2 "	[«rsync_args»] source [source …] dest"
		print -u2
		exec rsync --help
		;;
	(--sshkey=*)
		sshx="$sshx -i '${args[i]#*=}'"
		unset args[i]
		;;
	(--inplace)
		is_inplace=1
		;;
	(--no-numeric-ids)
		numeric_ids=
		unset args[i]
		;;
	(--numeric-ids)
		numeric_ids=--numeric-ids
		unset args[i]
		;;
	(-*)
		;;
	(*)
		break
		;;
	}
	let ++i
done

if (( is_inplace )); then
	use_sparse=
else
	use_sparse=-S
fi

exec rsync -z${a}vPH $numeric_ids $use_sparse --stats "$sshx" "${args[@]}"
