#!/bin/mksh
#-
# shuffle file descriptors around to make mplayer work
# with _remfor{,nd} and remote MP3 files — bufmplayer,
# in useful-scripts.git, appears to not work there but
# only for videos
#
# use as: _remfornd host path rmplayer -demuxer 17

exec mplayer "$@" /dev/fd/4 4<&0 0<&2
