#!/bin/mksh
# distinguish between various regular expression types
# • PCRE means Perl-compatible regex (man perlre), also PHP and Python
# • ERE are POSIX Extended Regular Expressions, optionally broken by GNU
# • BRE are POSIX Basic Regular Expressions, GNU or BSD flavours
# • ARE are Tcl/PostgreSQL Advanced Regular Expressions
#-
# © 2020 mirabilos Ⓕ The MirOS Licence

totest=$(sed -n '/^foo/p' <"$0") # read text to test from below
bsd='false' #'ssh mirbsd'
while IFS= read -r re?'RE: '; do
	# convert into PHP/Python/Tcl syntax
	pat=${re#s/}
	lim=1 cnt=1 flag=
	[[ $pat = *g ]] && lim=-1 cnt=0 flag=-all
	pat=${pat%/?(g)}
	rpl=${pat##*/}
	pat=${pat%/"$rpl"}
	phppat=\'/${pat@/[\\\']/\\$KSH_MATCH}/\'
	pypat=\'${pat@/[\\\']/\\$KSH_MATCH}\'
	prpl=\'${rpl@/[\\\']/\\$KSH_MATCH}\'
	# test the pattern
	print -r -- "$totest" | perl -pe "$re" | sed 's/^/Perl\t/'
	print -r -- "$totest" | php -r "
		echo preg_replace($phppat, $prpl,
		    file_get_contents('php://stdin'), $lim);
	    " | sed 's/^/PHP\t/'
	print -nr -- "$totest" | python3 -c "if True: # Python sux
		import re
		import sys
		print(re.sub($pypat, $prpl, sys.stdin.read(), $cnt))
	    " | sed 's/^/Py3k\t/'
	print -r -- "puts [regsub $flag {$pat} [lindex \$::argv 1] {$rpl}]" | \
	    tclsh - "$totest" | sed 's/^/Tcl\t/'
	print -r -- "$totest" | sed -E "$re" | sed 's/^/GNU ERE\t/'
	print -r -- "$totest" | sed -E --posix "$re" | sed 's/^/POSIX "\t/'
	print -r -- "$totest" | sed "$re" | sed 's/^/GNU BRE\t/'
	print -r -- "$totest" | sed --posix "$re" | sed 's/^/POSIX "\t/'
	print -r -- "$totest" | $bsd sed "${re@Q}" | sed 's/^/BSD BRE\t/'
done
exit 0

‣ The following line is the text we test:

foo bar Baaa+l \ ca

‣ You first decide how discriminative an answer you require:

 ① Just which class (PCRE, ARE, ERE, BRE)?

  s/(\A.*\B|$)/x/
	xa			PCRE: Perl, PHP, Python 3
	x ca			ARE: Tcl
	foo bar Baaa+l \ cax	ERE: GNU, POSIX
	foo bar Baaa+l \ ca	BRE: GNU, POSIX, BSD

 ② Which class and software?

  s/\s?(\ubaaa|\u006C|\x63|$)(.*\B)?/x$1/
	foo bar Baaa+x$1 ca	ARE: Tcl
	foo bar Baaa+x$1a	PCRE: Python3
	foo barxBaaaa		PCRE: Perl
	foo bar Baaa+l \xca	PCRE: PHP
	foo bar Baaa+l \x$1a	ERE: GNU
	foo bar Baaa+l \ x$1a	ERE: POSIX
	foo bar Baaa+l \ ca	BRE: GNU, POSIX, BSD

‣ If you got BRE, check if GNU incompatible extensions are present:

 s/B.*a\+./foo/
	foo bar fool \ ca	BRE: GNU
	foo bar foo \ ca	all others

‣ If you got POSIX BRE, optionally see whether BSD extensions are present:

 s/ca[[:>:]]/x/
	foo bar Baaa+l \ x	BRE: BSD, ARE: Tcl, PCRE: PHP
	foo bar Baaa+l \ ca	PCRE: Perl, (with a warning) Python3
	<Invalid character class name> in GNU sed (POSIX and GNU modes)
