#!/bin/mksh
# -*- mode: sh -*-
#-
# Copyright © 2014
#	Dominik George <dominik.george@teckids.org>
#	mirabilos <thorsten.glaser@teckids.org>
#
# Provided that these terms and disclaimer and all copyright notices
# are retained or reproduced in an accompanying document, permission
# is granted to deal in this work without restriction, including un‐
# limited rights to use, publicly perform, distribute, sell, modify,
# merge, give away, or sublicence.
#
# This work is provided “AS IS” and WITHOUT WARRANTY of any kind, to
# the utmost extent permitted by applicable law, neither express nor
# implied; without malicious intent or gross negligence. In no event
# may a licensor, author or contributor be held liable for indirect,
# direct, other damage, loss, or other issues arising in any way out
# of dealing in the work, even if advised of the possibility of such
# damage or existence of a defect, except proven that it results out
# of said person’s immediate fault when using the work as intended.

me=$(realpath "$0")

if [[ $GIT_SSH != "$me" ]]; then
	print "E: do not call me directly!" >/dev/tty
	exit 255
fi

if ! ssh -S "$TECKIDS_SSHCP/mux" -O check "$TECKIDS_MANAGEMENT_HOST" 2>/dev/null; then
	print "W: teckids ssh muxmaster not running!" >/dev/tty
	ssh -S "$TECKIDS_SSHCP/mux" -fNM "$TECKIDS_MANAGEMENT_HOST"
fi

exec ssh -S "$TECKIDS_SSHCP/mux" "$@"
