#!/bin/mksh
# $MirOS: contrib/hosted/tg/deb/aguspeed.sh,v 1.6 2024/01/06 01:35:43 tg Exp $
#-
# © 2011, 2012, 2019 mirabilos Ⓕ CC0 or MirBSD
#
# Use example:
#  agus -o Acquire::Check-Valid-Until=false   # on jessie
#  agus --allow-releaseinfo-change            # when testing changes

unset LANGUAGE
export LC_ALL=C

(( USER_ID )) && exec sudo mksh "$0" "$@"

if [[ $1 = -f ]]; then
	fflag=1
	shift
else
	fflag=0
fi

rv=
set -x
apt-get "$@" update || rv=$?
dpkg --clear-avail || rv=${rv:-$?}
# this emits a harmless warning on squeeze and newer
dpkg --forget-old-unavail || rv=${rv:-$?}
(( fflag )) || if sa=$(whence -p sync-available); then
	# call with mksh due to *buntu bug
	mksh "$sa" || rv=${rv:-$?}
fi
exit $rv
