#!/bin/mksh

# run as root
(( USER_ID )) && exec sudo "$0" "$@"

# decide what to do
case x$1 {
(x|xauto)
	for a in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do echo ondemand >$a; done
	;;
(x1|xon)
	for a in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do echo performance >$a; done
	;;
(x0|xoff)
	for a in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do echo powersave >$a; done
	;;
(xstatus)
	;;
(*)
	print -r -- 'call with on/1, off/0, auto (default) or status'
	exit 1
	;;
}
grep . /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
exit 0
