#!/bin/mksh

# run as root
(( USER_ID )) && exec sudo "$0" "$@"

# run verbosely
set -x

# decide what to do
case x$1 {
(x|xauto)
	for a in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do echo ondemand >$a; done
	;;
(x1|xon)
	for a in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do echo performance >$a; done
	;;
(x0|xoff)
	for a in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do echo powersave >$a; done
	;;
(*)
	echo call with on/off/auto
	exit 1
	;;
}
exit 0
