#!/bin/bash
# $MirOS: contrib/hosted/tg/deb/hookdir/A50wait,v 1.4 2023/01/28 04:04:02 tg Exp $
#-
# © 2011 mirabilos Ⓕ CC0
#
# This is actually POSIX sh compliant, except many do not do arithmetics.

:>/waiting
i=1
while [ -e /waiting ]; do
	i=$((i-1))
	if [ $i = 0 ]; then
		echo
		ls -l /waiting
		echo -n 'Waiting '
		i=300
	fi
	if [ $((i%5)) = 0 ]; then
		echo -n .
	fi
	sleep 2
done
echo
echo Continuing.
exit 0
