#!/bin/sh
# $MirOS: contrib/hosted/tg/deb/hookdir/B20lintian,v 1.2 2011/12/17 22:33:34 tg Exp $
#-
# Not complicated enough for copyright.

unset LANGUAGE
LC_ALL=C; export LC_ALL

ir=--install-recommends
# arrrrrgh!
apt-get install $ir -s apt >/dev/null 2>&1 || ir=
apt-get --purge -y install $ir lintian

argE=
argP=
if lintian -h 2>&1 | grep -F -- --display-experimental >/dev/null 2>&1; then
	argE=--display-experimental
fi
if lintian -h 2>&1 | grep -F -- --pedantic >/dev/null 2>&1; then
	argP=--pedantic
fi
echo
echo ==================================================================
echo Running lintian...
echo
extraargs=
for f in /tmp/buildd/*.changes; do
	case $f in
	(*snapshot.*)
		extraargs='-X nmu'
		;;
	esac
done
lintian -vIi $argE $argP $extraargs --allow-root /tmp/buildd/*.changes 2>&1
echo
echo ==================================================================
echo
