#!/bin/sh
# $MirOS: contrib/hosted/tg/deb/hookdir/B20lintian,v 1.6 2024/01/03 23:26:48 tg Exp $
#-
# © 2011, 2020 mirabilos Ⓕ CC0 or MirBSD

unset LANGUAGE
LC_ALL=C; export LC_ALL

apt-get --purge -y -o APT::Install-Recommends=true install lintian

argE=
argP=
if lintian -h 2>&1 | grep -F -- --display-experimental >/dev/null 2>&1; then
	argE=--display-experimental
fi
if lintian -h 2>&1 | grep -F -- --pedantic >/dev/null 2>&1; then
	argP=--pedantic
fi
echo
echo ==================================================================
echo Running lintian...
echo
extraargs=
for f in /tmp/buildd/*.changes; do
	case $f in
	(*snapshot.*)
		extraargs='-X nmu'
		break ;;
	esac
done
# omit --verbose on sarge where it displays overridden tags
dpkg --compare-versions "$(dpkg-query -W --showformat='${Version}' \
    lintian)" lt 1.23.28 || extraargs="$extraargs -v"
lintian -Ii $argE $argP $extraargs --allow-root /tmp/buildd/*.changes 2>&1
echo
echo ==================================================================
echo
