#!/bin/sh
# $MirOS: contrib/hosted/tg/deb/hookdir/B80shell-jupp,v 1.1 2023/01/28 04:04:02 tg Exp $
#-
# © 2012, 2013, 2014, 2016, 2021 mirabilos Ⓕ CC0

this=B80shell-jupp
msg() {
	local level=$1
	shift
	printf >&2 '%s: %s: %s\n' "$level" "$this" "$*"
}

unset LANGUAGE
LC_ALL=C; export LC_ALL

msg I "Current time: $(date)"
echo
echo Build succeeded. Trying to invoke a shell.
echo
apt-get -y install less mksh ed jupp || \
    apt-get -y install less mksh ed joe
ENV=/etc/skel/.mkshrc /bin/mksh -l 0<>/dev/tty >&0 2>&0 || \
    /bin/sh 0<>/dev/tty >&0 2>&0
