#!/bin/sh
# $MirOS: contrib/hosted/tg/deb/hookdir/C80shell-jupp,v 1.7 2021/06/13 17:24:04 tg Exp $
#-
# Not complicated enough for copyright.
#
# This can also be used as an A/B/D hook. Mind it installs packages.

unset LANGUAGE
LC_ALL=C; export LC_ALL

echo "I: Current time: $(date)"
echo
echo Build failed. Trying to invoke a shell.
echo
apt-get -y install less mksh ed jupp || \
    apt-get -y install less mksh ed joe
ENV=/etc/skel/.mkshrc /bin/mksh -l 0<>/dev/tty >&0 2>&0 || \
    /bin/sh 0<>/dev/tty >&0 2>&0
