#!/bin/sh
# $MirOS: contrib/hosted/tg/deb/hookdir/C80shell-jupp,v 1.3 2013/02/06 18:27:04 tg Exp $
#-
# Not complicated enough for copyright.

unset LANGUAGE
LC_ALL=C; export LC_ALL

echo "I: Current time: $(date)"
echo
echo Build failed. Trying to invoke a shell.
echo
apt-get -y --force-yes install less mksh ed jupp
ENV=/etc/skel/.mkshrc /bin/mksh -l 0<>/dev/tty >&0 2>&0 || \
    /bin/sh 0<>/dev/tty >&0 2>&0
