#!/bin/sh
# $MirOS: contrib/hosted/tg/deb/hookdir/D00-preseed,v 1.3 2023/01/28 04:04:03 tg Exp $
#-
# © 2017 mirabilos Ⓕ CC0

unset LANGUAGE
LC_ALL=C; export LC_ALL
set -e

set -v
debconf-set-selections <<\EOF
man-db man-db/build-database boolean false
man-db man-db/auto-update boolean false
EOF
