#!/bin/sh
# $MirOS: contrib/hosted/tg/deb/hookdir/D00-pins,v 1.4 2024/01/03 23:26:49 tg Exp $
#-
# © 2020 mirabilos Ⓕ CC0 or MirBSD

this=D00-pins
if test -d /etc/apt/preferences.d; then
	pfile=/etc/apt/preferences.d/$this.pref
else
	pfile=/etc/apt/preferences
fi
unset LANGUAGE
LC_ALL=C; export LC_ALL

# depends on systemd, gconf-gsettings-backend replaces it
#XXX not useful in *any* Debian release any more, do not activate this
cat >>"$pfile" <<\EOF
Package: dconf-gsettings-backend
Pin: version *
Pin-Priority: -1

EOF

exit 0
