#!/bin/sh
# $MirOS: contrib/hosted/tg/deb/hookdir/D00-identify,v 1.3 2023/01/29 11:05:55 tg Exp $
#-
# © 2021 mirabilos Ⓕ CC0

this=D00-identify
msg() {
	local level=$1
	shift
	printf >&2 '%s: %s: %s\n' "$level" "$this" "$*"
}

unset LANGUAGE
LC_ALL=C; export LC_ALL
set -e

msg I "building on $(cat /etc/issue.net 2>&1)" \
    "(debian_version $(cat /etc/debian_version 2>&1))"

set -- debian_chroot PBUILDERSATISFYDEPENDSCMD isbackports DEB_BUILD_OPTIONS \
    APTCACHE BASEPATH BUILDPLACE BUILDDIR BUILDRESULT \
    BUILD_ARCH DISTRIBUTION
test x"$DISTRIBUTION" = x"$DIST" || set -- "$@" DIST
set -- "$@" ARCHITECTURE
test x"$ARCHITECTURE" = x"$ARCH" || set -- "$@" ARCH

for var in "$@"; do
	eval "v=\${$var}" || continue
	test -n "$v" || continue
	msg N "$var=$v"
done

msg I "$(uname -a)"
exit 0
