#!/bin/sh
# $MirOS: contrib/hosted/tg/deb/hookdir/D02debhelper,v 1.1 2009/12/28 19:29:06 tg Exp $
#-
# Not complicated enough for copyright.

dpkg -i /tmp/debhelper*deb
apt-get -y --force-yes -o Dpkg::Options::=--force-confnew,confmiss -f install
