#!/bin/sh
# $MirOS: contrib/hosted/tg/deb/hookdir/D02debhelper,v 1.4 2016/01/14 18:46:20 tg Exp $
#-
# Not complicated enough for copyright.

unset LANGUAGE
LC_ALL=C; export LC_ALL

dpkg -i /tmp/debhelper*deb
apt-get -y -o Dpkg::Options::=--force-confnew,confmiss -f install
