#!/bin/sh
# $MirOS: contrib/hosted/tg/deb/hookdir/D06agdu,v 1.2 2012/01/03 16:57:19 tg Exp $
#-
# Not complicated enough for copyright.

unset LANGUAGE
LC_ALL=C; export LC_ALL

#cat >/etc/resolv.conf <<'EOF'
#lookup file bind
#nameserver 8.8.8.8
#EOF

apt-get update
apt-get -y --purge dist-upgrade
