#!/bin/sh
# $MirOS: contrib/hosted/tg/deb/hookdir/D10wtfrepo,v 1.5 2016/08/23 18:02:06 tg Exp $
#-
# Not complicated enough for copyright.

unset LANGUAGE
LC_ALL=C; export LC_ALL

d=${DIST%/*}
d=${d%-backports*}
case $d in
(sarge|etch|lenny|squeeze|wheezy|jessie|sid)
	;;
(stretch|buster|bullseye)
	d=sid
	;;
(*)
	echo >&2 W: D10wtfrepo: ignoring unknown DIST "'$DIST'"
	exit 0
	;;
esac

# Import 2015 key
apt-key add - <<'EOF'
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.14 (MirBSD)

mQGNBFSNsycBDADQdl54UXf9oXNjOSjwnzopJbeaK5CJ8tvotnVv69KUg0VGUzkx
lndV8rBvg8mWnRq8hWeEQNw0Yt2TDt1kg/cuo3NX+1xrMcfFyeeXxQhFewkd9SSO
71EnGaG1NnHytzFx1olcs74aOzXAvyIson86dvwp1oSKrFeyvVpY7X7eltzkeM9X
2bpmNWl06NjmgLg5Pmboh6EGAQh6Zpk4zVl5nC1Gq0lYYnYuJNHoSwA3RQCH3zST
Im8gKh98smZ8dVaOK7rWzQvSQiWXpkZ2fzWsF4e2sNbwCW+FWHLHM89BLJiPO4k0
wEEkBWguYCpddUMWwfmewWzxFU8fjhxiTq31MJSrt4r5LLwh0N1GGQXp2soCmsAN
gT1qIV3UUJb3Ion/0iiQSqCnDNZjFlaGziPIiezU4pavOl7+fUy0vq4RXac8f2TJ
fda8Hk3uNRRlQAlcMc00mn0a3rdYFGGempitl29c3C4GarD7M3sXwcR/0xBDJnkQ
ZRVTfNFYB91BpJEAEQEAAYkBtwQfAQkAIQUCVI2zJxcMgAGQMZVeepek/aMrK4Z2
tTSy6ZAH4AIHAAAKCRAwwGD6ILJPR7KlC/9aNtjsuWCnLC8s4h+m5bJBvciLci14
0/JNOkj9982r6ijtrorcu0krpkZV2uZlrWy6veER6uMMjKynKY8HD0KSkTZu6XJ+
YYf4tAjaEsr+AOQIIZuuKUR1XT9tMJ9uQwZ/ZIXtGz6sulYmkvi+0dQpzLI7YfoW
83PfujnBopU3CyMJR63eAlkmJBo/QWwrB4XEfGVZ765H5j/wMxb5Vzr8s/ZpGzQ6
KDWYIHO49A7ShGGAq8oSAJbtqtBLkVCw63l1/CetPFBQMKnsZNUie0s04gOUvMBn
oWp6+KL3RjWLsDV62/yHJfjATQ56UmgQztYbqc3VFDIQrO9c+reAItnNdNxdXjob
+c0ixCT4SYCas73Y9fi5fV5D3Lx/aIcBJmKONSfYcizkdDAs0eZpRbbdpggEaiBV
2XFcMYrMDq3ZOsSn3/YTpYTn+ZT+jQB/Bf75nzZvNWPIKaeu5lw2ClcOdZ5z7r37
DY2VSfUYLGbuXaPA37Bu0IhpRIfQULO4num0MVNpZ25pbmcga2V5IDIwMTUgZm9y
IOKAnFdURuKAnSBwYWNrYWdlIHJlcG9zaXRvcnmJAdEEEwEJADsFAlSNsycCGwMF
CQW7xvIFCwgECQcFFQkKAwgDFgIAAh4BAheAFRhoa3A6Ly9wZ3Auc3VyZm5ldC5u
bAAKCRAwwGD6ILJPR3AMC/9Q2lXxARjdmZ+99/0zv5I/PFlUIY402uH0ryajIzZ6
yCIbw85n32IE66BRs2YSyVDv9yK58btAx1zuvTM3HxkVHt76lQcVEPRSZnJKJErI
J6h27nj5HDsJDs9dq3BK4xcN/Qv+YMtbNg7Rr0x3bYR7+vRTiNvnVIaqe78AvDfm
zRgkAuUckbcyprSxB5wcMolPJsePDeWXNEsOHqMEQ5Kud2az7shCam361PtUHDHp
nJD9piSzb7JnConxbkvMp+ulEfQyUYI+XMBOpGT+d+dyVnhgXy+StcS5lV8rEUYy
DXKTpHI1AzJrdRpH1NgHz+r4GbRHbJ/gH2TbtXPq7mCswlVdzcTLZiQD/0TG4UZP
gENBqZrRjMxIywm04sv4UjybIwHJikeYNMgmlk8hWKdt5mvIioBTxq6r8BifbA/1
nBSnBj7EHBDFcWHKwfmXf8DEaznk8tPPLAJ5ZPv3HkqfPYBBvXJ26gQN/TzXM24p
sptjizYTgjcFMaB/hIYnoNM=
=Ar55
-----END PGP PUBLIC KEY BLOCK-----
EOF

cat >>/etc/apt/sources.list <<EOF
deb http://www.mirbsd.org/~tg/Debs/ $d wtf
EOF

apt-get update
apt-get -y --purge dist-upgrade
