#!/bin/sh
# $MirOS: contrib/hosted/tg/deb/hookdir/D10wtfrepo,v 1.14 2023/01/28 04:56:50 tg Exp $
#-
# © 2012, 2014, 2016, 2017, 2023 mirabilos Ⓕ CC0

this=D10wtfrepo
msg() {
	local level=$1
	shift
	printf >&2 '%s: %s: %s\n' "$level" "$this" "$*"
}

unset LANGUAGE
LC_ALL=C; export LC_ALL
set -e
mydir=$(dirname "$0")
if test -d /etc/apt/sources.list.d; then
	slist=/etc/apt/sources.list.d/$this.list
else
	slist=/etc/apt/sources.list
fi

d=${DIST%/*}
d=${d%-backports*}
dokey=
case $d in
(sarge|etch|lenny|squeeze|wheezy|jessie|stretch|buster|bullseye)
	dokey=1
	;;
(bookworm)
	;;
(trixie|forky)
	msg W adding stable for testing
	d=bookworm
	;;
(sid)
	;;
(dpo)
	d=sid
	;;
(*)
	msg W ignoring unknown DIST "'$DIST'"
	exit 0
	;;
esac

# 2018 key
repokey=$(cat <<'EOF'
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQGNBFlP41MBDADGjAsxl0jbdknmg2CHKf7gQPBxOBk5/qw6F5HAOthBM/14sohA
iwXyXW7oEcmPAKc7v8yn+A/JjrCfsp6rXUnMlB37zr5qb0JIO1o3p0guekGGJ/in
48NClFMQU71MmOvaRWIKrNVtFIhLcFncCU9k6bB1hCnhhSmHGBlsIIGhInIHbv4o
5IZYKb0BWJ1SqiOLAwYblstUIcFGR2K+z3l+hwFgMFM0VhMCi0fCyrdEWw9Qs1I1
l0K3hzG2WUOhWO+aY4qoOyPlMc3a9zXBFdc0JHptRgh3JTBf2gK3kO6wcPfdG5Hq
btCstesRFYS9nOoKwyxg80iZYpV4+q6POeS43Xfi2APXB+3tXAQJ5+dCYam/jlzu
oyPAEZxai5R8m1q9SD+c16nx8F5GSuEoAcvfyAc7EqhCfnjh3o2/QokOPPboMRWW
s46FaIWZiuNf8p1hfgj6cjH1ny124AbvvClddCDPuFwwXVxRji3ApeOwPUkqoFDn
zebsA4OA2+ggEGEAEQEAAbQxU2lnbmluZyBrZXkgMjAxOCBmb3Ig4oCcV1RG4oCd
IHBhY2thZ2UgcmVwb3NpdG9yeYkBuwQTAQkAJQIbAwULCAQJBwUVCQoDCAMWAgAC
HgECF4AFAmPUf44FCREBvi4ACgkQAgir6mZzodktTgv9E48RRmVBXg8bVHxEjnvd
NQY3b/KjACzcs9iKVE1gPG0wrdo3DzCDhCfuIqeofz6/KWeoZUZi9NpJV8JIrzxZ
wjQAFAckuGhBRHo4OOEzYW+YyJMdWa1btM2qYy0YgBI4VJpbSQubW7s+iYosF4qg
639tj0rRmBvScWvqKy0o/VxE4HvsZfq5abL/C4txpummmYuo7qHapoLNAgXylfoB
Z5xrRwZR64rLiIupkP8OwxF0oAXLvNrxN6CLJ3xBYCoaYU2phtA9b56FucGh6cts
CMpivK9iYt6GexFNw9DWxEffCRSdsT8uSp3CfktVb7BK0hjbQbZUvsDY870akRpx
G7c0D/iOK/lPpdAc/NXmCeM8dFWa6GaIc72cg60Nh9nrHedygALV7jY2wVxQRXgJ
RlU7iWE/Y56OcGQ6vERGK5ZpUN8sGS8EX2daltMBAyaA3xQ9LjCCE6uNAtIl89Yc
1Fz5a02YLhd3YU39gbgx+vSKvBik5VO4o7mvLfEySR/n
=z3/K
-----END PGP PUBLIC KEY BLOCK-----
EOF
)

if test -n "$dokey"; then
	# in bullseye, this already emits a warning…
	printf '%s\n' "$repokey" | apt-key add -
	cat >>"$slist" <<-EOF
		deb http://www.mirbsd.org/~tg/Debs/ $d wtf
	EOF
else {
	echo 'Types: deb'
	echo 'URIs: http://www.mirbsd.org/~tg/Debs/'
	echo "Suites: $d"
	echo 'Components: lts'
	echo 'Languages: none'
	# … but this isn’t supported yet in bullseye, so pooh!
	echo Signed-By:
	printf '%s\n' "$repokey" | sed -e 's/^$/./' -e 's/^/ /'
    } >"/etc/apt/sources.list.d/$this.sources"
fi

case $d in
(sarge)
	# suite dependency
	grep sarge-backports /etc/apt/sources.list >/dev/null 2>&1 || \
	    msg W 'missing sarge-backports'
	# note apt-key is in apt/sarge-backports so install that first
	;;
(squeeze)
	# partial suite, add base
	cat >>"$slist" <<-EOF
		deb http://www.mirbsd.org/~tg/Debs/ lenny wtf
	EOF
	;;
esac

if test -x "$mydir/D50apt-update" || \
    test -x "$mydir/D50apt-upgrade"; then
	: 'nothing; rely on the operator to DTRT'
else
	apt-get update
	apt-get -y --purge dist-upgrade
fi
