#!/bin/sh
# $MirOS: contrib/hosted/tg/deb/hookdir/D25backports,v 1.11 2024/01/03 23:26:51 tg Exp $
#-
# © 2012, 2014, 2016, 2017, 2018, 2019, 2022, 2023 mirabilos Ⓕ CC0 or MirBSD
#
# Note: Secure APT is a PITA, for old versions.
#
# Note: This will not work with pbuilder-satisfydepends-classic,
# and on sarge not with pbuilder-satisfydepends (aptitude) either.
# On stretch (new enough for pbuilder-satisfydepends-apt) it will
# not work with that, but with pbuilder-satisfydepends-aptitude…

this=D25backports
msg() {
	local level=$1
	shift
	printf >&2 '%s: %s: %s\n' "$level" "$this" "$*"
}

unset LANGUAGE
LC_ALL=C; export LC_ALL
set -e
mydir=$(dirname "$0")
if test -d /etc/apt/sources.list.d; then
	slist=/etc/apt/sources.list.d/$this.list
else
	slist=/etc/apt/sources.list
fi

d=${DIST%/*}
d=${d%-backports*}
case $d in
(sarge|etch|lenny|squeeze)
	echo deb http://archive.debian.org/debian-backports/ \
	    $d-backports main >>"$slist"
	;;
(wheezy|jessie)
	echo deb http://archive.debian.org/debian/ \
	    $d-backports main >>"$slist"
	;;
(stretch|buster|bullseye|bookworm)
	echo deb http://deb.debian.org/debian/ \
	    $d-backports main >>"$slist"
	;;
(dapper|hardy|jaunty|karmic|lucid|maverick|natty|oneiric|precise|quantal|raring|saucy|utopic|vivid|wily|yakkety|zesty|artful|cosmic|disco|eoan|groovy|hirsute|impish)
	echo deb http://old-releases.ubuntu.com/ubuntu/ \
	    $d-updates main universe >>"$slist"
	echo deb http://old-releases.ubuntu.com/ubuntu/ \
	    $d-backports main universe >>"$slist"
	;;
(trusty|xenial|bionic|focal|jammy|kinetic|lunar)
	echo deb http://archive.ubuntu.com/ubuntu/ \
	    $d-updates main universe >>"$slist"
	echo deb http://archive.ubuntu.com/ubuntu/ \
	    $d-backports main universe >>"$slist"
	;;
(*)
	msg W ignoring unknown DIST "'$DIST'"
	exit 0
	;;
esac

# specific workarounds
case $d/$ARCHITECTURE in
(stretch/amd64)
	# cmake is broken in the last upload
	echo deb \[arch=amd64 check-valid-until=no\] \
	    http://snapshot.debian.org/archive/debian/20190105T031603Z/ \
	    stretch-backports main >>"$slist"
	;;
esac

if test -x "$mydir/D50apt-update" || \
    test -x "$mydir/D50apt-upgrade"; then
	: 'nothing; rely on the operator to DTRT'
else
	apt-get update
	#apt-get -y --purge dist-upgrade
fi
