#!/bin/sh
# $MirOS: contrib/hosted/tg/deb/hookdir/D25backports,v 1.8 2020/10/31 07:21:35 tg Exp $
#-
# Not complicated enough for copyright.
#
# Note: Secure APT is a PITA, for old versions.
#
# Note: This will not work with pbuilder-satisfydepends-classic,
# and on sarge not with pbuilder-satisfydepends (aptitude) either.
# On stretch (new enough for pbuilder-satisfydepends-apt) it will
# not work with that, but with pbuilder-satisfydepends-aptitude…

unset LANGUAGE
LC_ALL=C; export LC_ALL

d=${DIST%/*}
d=${d%-backports*}
case $d in
(sarge|etch|lenny|squeeze)
	echo deb http://archive.debian.org/debian-backports/ \
	    $d-backports main >>/etc/apt/sources.list
	;;
(wheezy|jessie)
	echo deb http://archive.debian.org/debian/ \
	    $d-backports main >>/etc/apt/sources.list
	;;
(stretch|buster|bullseye)
	echo deb http://deb.debian.org/debian/ \
	    $d-backports main >>/etc/apt/sources.list
	;;
(dapper|hardy|jaunty|karmic|lucid|maverick|natty|oneiric|quantal|raring|saucy|utopic|vivid|wily|yakkety|zesty|artful|cosmic|disco)
	echo deb http://old-releases.ubuntu.com/ubuntu/ \
	    $d-updates main universe >>/etc/apt/sources.list
	echo deb http://old-releases.ubuntu.com/ubuntu/ \
	    $d-backports main universe >>/etc/apt/sources.list
	;;
(precise|trusty|xenial|bionic|eoan|focal|groovy|hirsute)
	echo deb http://archive.ubuntu.com/ubuntu/ \
	    $d-updates main universe >>/etc/apt/sources.list
	echo deb http://archive.ubuntu.com/ubuntu/ \
	    $d-backports main universe >>/etc/apt/sources.list
	;;
(*)
	echo >&2 W: D25backports: ignoring unknown DIST "'$DIST'"
	exit 0
	;;
esac

apt-get update
