#!/bin/sh
# $MirOS: contrib/hosted/tg/deb/hookdir/D26backportsloppy,v 1.5 2025/04/25 19:55:32 tg Exp $
#-
# © 2012, 2014, 2016, 2017, 2019, 2023 mirabilos Ⓕ CC0 or MirBSD

this=D26backportsloppy
msg() {
	local level=$1
	shift
	printf >&2 '%s: %s: %s\n' "$level" "$this" "$*"
}

unset LANGUAGE
LC_ALL=C; export LC_ALL
set -e
mydir=$(dirname "$0")
if test -d /etc/apt/sources.list.d; then
	slist=/etc/apt/sources.list.d/$this.list
else
	slist=/etc/apt/sources.list
fi

d=${DIST%/*}
d=${d%-backports*}
case $d in
(lenny)
	apt-get -y --purge install debian-backports-keyring
	echo deb http://archive.debian.org/debian-backports/ \
	    $d-backports-sloppy main >>"$slist"
	;;
(squeeze)
	echo deb http://archive.debian.org/debian-backports/ \
	    $d-backports-sloppy main >>"$slist"
	;;
(wheezy|jessie|stretch|buster)
	echo deb http://archive.debian.org/debian/ \
	    $d-backports-sloppy main >>"$slist"
	;;
(bullseye|bookworm)
	echo deb http://deb.debian.org/debian/ \
	    $d-backports-sloppy main >>"$slist"
	;;
(*)
	msg W ignoring unknown DIST "'$DIST'"
	exit 0
	;;
esac

if test -x "$mydir/D50apt-update" || \
    test -x "$mydir/D50apt-upgrade"; then
	: 'nothing; rely on the operator to DTRT'
else
	apt-get update
	#apt-get -y --purge dist-upgrade
fi
