#!/bin/sh
# $MirOS: contrib/hosted/tg/deb/hookdir/D29dhbpo,v 1.1 2018/12/20 01:48:12 tg Exp $
#-
# Not complicated enough for copyright.
#
# Evil hack, to go with D25backports, when necessary.

unset LANGUAGE
LC_ALL=C; export LC_ALL

d=${DIST%/*}
d=${d%-backports*}

apt-get -y install debhelper/$d-backports
