#!/bin/sh
# $MirOS: contrib/hosted/tg/deb/hookdir/D29dhbpo,v 1.2 2022/11/17 10:43:10 tg Exp $
#-
# Not complicated enough for copyright.
#
# Evil hack, to go with D25backports, when necessary.

unset LANGUAGE
LC_ALL=C; export LC_ALL

d=${DIST%/*}
d=${d%-backports*}

apt-get -y install debhelper
apt-get -y install -t $d-backports debhelper
