#!/bin/sh
# $MirOS: contrib/hosted/tg/deb/hookdir/D50apt-update,v 1.2 2024/01/03 23:26:48 tg Exp $
#-
# © 2011 mirabilos Ⓕ CC0 or MirBSD

unset LANGUAGE
LC_ALL=C; export LC_ALL
set -e

#rm -f /etc/resolv.conf
#cat >/etc/resolv.conf <<'EOF'
#lookup file bind
#nameserver 8.8.8.8
#EOF

apt-get update
