#!/bin/sh
# $MirOS: contrib/hosted/tg/deb/hookdir/D60backports-debhelper,v 1.2 2024/01/03 23:26:50 tg Exp $
#-
# © 2018, 2022 mirabilos Ⓕ CC0 or MirBSD
#
# Evil hack, to go with D25backports, when necessary.

unset LANGUAGE
LC_ALL=C; export LC_ALL
set -e

d=${DIST%/*}
d=${d%-backports*}

apt-get -y --purge install debhelper
apt-get -y --purge install -t "$d-backports" debhelper
