#!/bin/sh
# $MirOS: contrib/hosted/tg/deb/hookdir/F01preseed,v 1.5 2024/01/03 23:26:50 tg Exp $
#-
# © 2017 mirabilos Ⓕ CC0 or MirBSD

unset LANGUAGE
LC_ALL=C; export LC_ALL
set -e

set -v
debconf-set-selections <<\EOF
man-db man-db/build-database boolean false
man-db man-db/auto-update boolean false
EOF
