#!/bin/mksh
# $MirOS: contrib/hosted/tg/deb/hookdir/pbuild,v 1.1 2009/12/07 20:48:19 tg Exp $
#-
# Not complicated enough for copyright.

unset LANG LANGUAGE LC_ADDRESS LC_COLLATE LC_CTYPE LC_IDENTIFICATION \
    LC_MEASUREMENT LC_MESSAGES LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER \
    LC_TELEPHONE LC_TIME
export LC_ALL=C
exec sudo cowbuilder --hookdir $(realpath .)/pb-hook "$@"
