#!/bin/mksh
# $MirOS: contrib/hosted/tg/deb/hookdir/pbuild,v 1.3 2011/06/09 22:17:15 tg Exp $
#-
# Not complicated enough for copyright.

DIST=$(realpath "$0")
DIST=${DIST##*/dists/}
DIST=${DIST%%/*}

unset LANG LANGUAGE LC_ADDRESS LC_COLLATE LC_CTYPE LC_IDENTIFICATION \
    LC_MEASUREMENT LC_MESSAGES LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER \
    LC_TELEPHONE LC_TIME
export LC_ALL=C DIST
exec sudo cowbuilder --hookdir $(realpath .)/pb-hook "$@"
