#!/bin/mksh
# -*- mode: sh -*-
#-
# Copyright © 2014
#	mirabilos <thorsten.glaser@teckids.org>
#
# Provided that these terms and disclaimer and all copyright notices
# are retained or reproduced in an accompanying document, permission
# is granted to deal in this work without restriction, including un‐
# limited rights to use, publicly perform, distribute, sell, modify,
# merge, give away, or sublicence.
#
# This work is provided “AS IS” and WITHOUT WARRANTY of any kind, to
# the utmost extent permitted by applicable law, neither express nor
# implied; without malicious intent or gross negligence. In no event
# may a licensor, author or contributor be held liable for indirect,
# direct, other damage, loss, or other issues arising in any way out
# of dealing in the work, even if advised of the possibility of such
# damage or existence of a defect, except proven that it results out
# of said person’s immediate fault when using the work as intended.

script=$(realpath "$(dirname "$0")"/ldif_crc.sh)
[[ -s $script && -x $script ]] || exit 1

cd "${1:-/etc/ldap/slapd.d}" || exit 1
find . -type f -print0 |&
while IFS= read -pr -d '' name; do
	if [[ $name != *.ldif ]]; then
		print -ru2 -- "W: '$name' not *.ldif"
		continue
	fi
	content=$(cat "$name"; echo .)
	print -nr -- "${content%.}" | "$script" >"$name"
done
