#!/bin/mksh
# -*- mode: sh -*-
#-
# Copyright © 2014
#	mirabilos <m$(date +%Y)@mirbsd.de>
#
# Provided that these terms and disclaimer and all copyright notices
# are retained or reproduced in an accompanying document, permission
# is granted to deal in this work without restriction, including un‐
# limited rights to use, publicly perform, distribute, sell, modify,
# merge, give away, or sublicence.
#
# This work is provided “AS IS” and WITHOUT WARRANTY of any kind, to
# the utmost extent permitted by applicable law, neither express nor
# implied; without malicious intent or gross negligence. In no event
# may a licensor, author or contributor be held liable for indirect,
# direct, other damage, loss, or other issues arising in any way out
# of dealing in the work, even if advised of the possibility of such
# damage or existence of a defect, except proven that it results out
# of said person’s immediate fault when using the work as intended.

print -n '\033[0m'
for i in 0 1; do
	ii=0
	(( i )) && ii=0\;1
	is=
	(( i )) && is='1;'
	for bg in 4{0,1,2,3,4,5,6,7}; do
		for fg in 3{0,1,2,3,4,5,6,7}; do
			print -n "\033[$i;$fg;${bg}m ${is}$fg;${bg}m"
		done
		print '\033[0m'
	done
done
print -n '\033[0m'
