#!/bin/mksh
#-
# Copyright © 2013, 2014
#	Thorsten “mirabilos” Glaser <t.glaser@tarent.de>
#
# Provided that these terms and disclaimer and all copyright notices
# are retained or reproduced in an accompanying document, permission
# is granted to deal in this work without restriction, including un‐
# limited rights to use, publicly perform, distribute, sell, modify,
# merge, give away, or sublicence.
#
# This work is provided “AS IS” and WITHOUT WARRANTY of any kind, to
# the utmost extent permitted by applicable law, neither express nor
# implied; without malicious intent or gross negligence. In no event
# may a licensor, author or contributor be held liable for indirect,
# direct, other damage, loss, or other issues arising in any way out
# of dealing in the work, even if advised of the possibility of such
# damage or existence of a defect, except proven that it results out
# of said person’s immediate fault when using the work as intended.
#-
# Simple-to-use wrapper around eatmydata plus cowbuilder to use with
# https://www.mirbsd.org/cvs.cgi/contrib/hosted/tg/deb/pbuilderrc to
# select the proper build chroot.
#
# Example:
# c lenny/i386 DEB_BUILD_OPTIONS=parallel=4 linux32 --build foo*.dsc

unset LANGUAGE
DIST=$1
eatmydata=eatmydata
case $DIST {
(sarge|sarge/i386|etch|etch/i386|etch/amd64)
	eatmydata=
	;;
}
eatmydata= #765579
set -A cmd env "DIST=$DIST" LANG=C LC_CTYPE=C LC_NUMERIC=C \
    LC_TIME=C LC_COLLATE=C LC_MONETARY=C LC_MESSAGES=C LC_PAPER=C \
    LC_NAME=C LC_ADDRESS=C LC_TELEPHONE=C LC_MEASUREMENT=C \
    LC_IDENTIFICATION=C LC_ALL=C $eatmydata
shift
while [[ $1 = *=* ]]; do
	cmd[${#cmd[@]}]=$1
	shift
done
setarch_seen=0
case $1 {
(--)
	shift
	;;
(linux32|linux64)
	cmd[${#cmd[@]}]=$1
	shift
	if [[ $1 = --uname-2.6 ]]; then
		cmd[${#cmd[@]}]=$1
		shift
	fi
	setarch_seen=1
	;;
}
#XXX add more architectures
(( setarch_seen )) || case $DIST {
(*/amd64) cmd[${#cmd[@]}]=linux64 ;;
(*/i386) cmd[${#cmd[@]}]=linux32 ;;
(*/x32) cmd[${#cmd[@]}]=linux64 ;;
(*) setarch_seen=2 ;;
}
(( setarch_seen )) || case ${DIST%/*} {
(sarge|sarge-*) cmd[${#cmd[@]}]=--uname-2.6 ;;
(etch|etch-*) cmd[${#cmd[@]}]=--uname-2.6 ;;
(lenny|lenny-*) cmd[${#cmd[@]}]=--uname-2.6 ;;
(squeeze|squeeze-*) cmd[${#cmd[@]}]=--uname-2.6 ;;
(dapper|dapper-*) cmd[${#cmd[@]}]=--uname-2.6 ;;
(hardy|hardy-*) cmd[${#cmd[@]}]=--uname-2.6 ;;
(jaunty|jaunty-*) cmd[${#cmd[@]}]=--uname-2.6 ;;
(karmic|karmic-*) cmd[${#cmd[@]}]=--uname-2.6 ;;
(lucid|lucid-*) cmd[${#cmd[@]}]=--uname-2.6 ;;
(maverick|maverick-*) cmd[${#cmd[@]}]=--uname-2.6 ;;
(natty|natty-*) cmd[${#cmd[@]}]=--uname-2.6 ;;
}

set -x
exec sudo "${cmd[@]}" cowbuilder "$@"
