#!/bin/mksh
# -*- mode: sh -*-
#-
# Copyright © 2013, 2014, 2018, 2020, 2021, 2024, 2025
#	mirabilos <m$(date +%Y)@mirbsd.de>
#
# Provided that these terms and disclaimer and all copyright notices
# are retained or reproduced in an accompanying document, permission
# is granted to deal in this work without restriction, including un‐
# limited rights to use, publicly perform, distribute, sell, modify,
# merge, give away, or sublicence.
#
# This work is provided “AS IS” and WITHOUT WARRANTY of any kind, to
# the utmost extent permitted by applicable law, neither express nor
# implied; without malicious intent or gross negligence. In no event
# may a licensor, author or contributor be held liable for indirect,
# direct, other damage, loss, or other issues arising in any way out
# of dealing in the work, even if advised of the possibility of such
# damage or existence of a defect, except proven that it results out
# of said person’s immediate fault when using the work as intended.
#-
# Simple-to-use wrapper around eatmydata plus cowbuilder to use with
# https://www.mirbsd.org/cvs.cgi/contrib/hosted/tg/deb/pbuilderrc to
# select the proper build chroot. Now relies on pbuilderrc to enable
# eatmydata and datefudge.
#
# Example:
# c lenny/i386 DEB_BUILD_OPTIONS=parallel=4 linux32 --build foo*.dsc
# c bp:stretch/i386 --debbuildopts -v1.0-1 foo*.dsc
# c bionic/amd64~neon --update

unset LANGUAGE
export LC_ALL=C

if (( USER_ID == 0)) && [[ -z ${SUDO+set} ]]; then
	# already root so omit the sudo call by default
	SUDO=
fi

set -A cmd -- env --unset=XDG_RUNTIME_DIR

if [[ -z $1 ]]; then
	print -u2 E: No operation specified
	exit 1
fi
REALDIST=$1
if [[ $1 = *'~'* ]]; then
	CUSTOM=${REALDIST#*'~'}
	set -A cmd+ -- "CUSTOM=$CUSTOM"
	REALDIST=${REALDIST%%'~'*}
fi
DIST=${REALDIST##*:}
shift

# construct command line
set -A cmd+ -- "DIST=$REALDIST" LANG=C LC_CTYPE=C LC_NUMERIC=C \
    LC_TIME=C LC_COLLATE=C LC_MONETARY=C LC_MESSAGES=C LC_PAPER=C \
    LC_NAME=C LC_ADDRESS=C LC_TELEPHONE=C LC_MEASUREMENT=C \
    LC_IDENTIFICATION=C LC_ALL=C
[[ -n $DATEFUDGE ]] && set -A cmd+ -- "DATEFUDGE=$DATEFUDGE"
while [[ $1 = *=* ]]; do
	cmd[${#cmd[@]}]=$1
	shift
done
setarch_seen=0
case $1 {
(--)
	shift
	;;
(linux32|linux64)
	cmd[${#cmd[@]}]=$1
	shift
	if [[ $1 = --uname-2.6 ]]; then
		cmd[${#cmd[@]}]=$1
		shift
	fi
	setarch_seen=1
	;;
}
#XXX add more architectures
case $DIST {
(*/amd64)	setarch_cmd=linux64 ;;
(*/i386)	setarch_cmd=linux32 ;;
(*/x32)		setarch_cmd=linux64 ;;
(*/*)		setarch_cmd= ;;
(*)		setarch_cmd=- ;;
}
[[ $REALDIST != q:* ]] || setarch_cmd=-
case ${DIST%/*} {
(sarge|sarge-*)		setarch_26=1 ;;
(etch|etch-*)		setarch_26=1 ;;
(lenny|lenny-*)		setarch_26=1 ;;
(squeeze|squeeze-*)	setarch_26=1 ;;
(dapper|dapper-*)	setarch_26=1 ;;
(hardy|hardy-*)		setarch_26=1 ;;
(jaunty|jaunty-*)	setarch_26=1 ;;
(karmic|karmic-*)	setarch_26=1 ;;
(lucid|lucid-*)		setarch_26=1 ;;
(maverick|maverick-*)	setarch_26=1 ;;
(natty|natty-*)		setarch_26=1 ;;
(*)			setarch_26=0 ;;
}
(( setarch_seen )) || case x$setarch_cmd {
(x)
	print -ru2 "W: no setarch for architecture part of '$REALDIST'!"
	;;
(x-)
	if (( setarch_26 )); then
		cmd[${#cmd[@]}]=setarch
		cmd[${#cmd[@]}]=uname26
		cmd[${#cmd[@]}]=--
	fi
	;;
(*)
	cmd[${#cmd[@]}]=$setarch_cmd
	(( setarch_26 )) && cmd[${#cmd[@]}]=--uname-2.6
	cmd[${#cmd[@]}]=--
	;;
}

unset TMPDIR
set -x
exec ${SUDO-sudo} "${cmd[@]}" cowbuilder "$@"
