#!/bin/mksh
#-
# Copyright © 2014, 2018, 2022
#	mirabilos <t.glaser@tarent.de>
#
# Provided that these terms and disclaimer and all copyright notices
# are retained or reproduced in an accompanying document, permission
# is granted to deal in this work without restriction, including un‐
# limited rights to use, publicly perform, distribute, sell, modify,
# merge, give away, or sublicence.
#
# This work is provided “AS IS” and WITHOUT WARRANTY of any kind, to
# the utmost extent permitted by applicable law, neither express nor
# implied; without malicious intent or gross negligence. In no event
# may a licensor, author or contributor be held liable for indirect,
# direct, other damage, loss, or other issues arising in any way out
# of dealing in the work, even if advised of the possibility of such
# damage or existence of a defect, except proven that it results out
# of said person’s immediate fault when using the work as intended.

function die {
	print -ru2 -- "E: $*"
	exit 1
}

[[ -s $1 ]] || die need package to extract

cd "$(realpath "$1/..")" || die cannot cd
fn=${1##*/}

[[ $fn = *.dsc ]] && exec dpkg-source -x "$fn"

[[ $fn = *.@(deb|ipk) ]] || die not a Debian source or binary package or IPK
dn=${fn%.???}-extracted

function x_member {
	set -o pipefail
	local fn

	for fn in "$@"; do
		# use filename to identify nōn-standard formats
		case $fn {
		(*.tar.zst)
			zstd -dc <"$fn" | paxtar xpf -
			;;
		(*)
			paxtar xapf "$fn"
			;;
		}
	done
}

mode=xapf
[[ $fn = *.ipk ]] && mode=xzpf

set -e
rm -rf "$dn"
mkdir "$dn"
cd "$dn"
paxtar $mode ../"$fn"
mkdir c d
cd c
x_member ../control.*
cd ../d
x_member ../data.*
