#!/bin/mksh
# -*- mode: sh -*-
#-
# Copyright © 2015, 2021, 2022, 2024, 2025
#	mirabilos <m$(date +%Y)@mirbsd.de>
#
# Provided that these terms and disclaimer and all copyright notices
# are retained or reproduced in an accompanying document, permission
# is granted to deal in this work without restriction, including un‐
# limited rights to use, publicly perform, distribute, sell, modify,
# merge, give away, or sublicence.
#
# This work is provided “AS IS” and WITHOUT WARRANTY of any kind, to
# the utmost extent permitted by applicable law, neither express nor
# implied; without malicious intent or gross negligence. In no event
# may a licensor, author or contributor be held liable for indirect,
# direct, other damage, loss, or other issues arising in any way out
# of dealing in the work, even if advised of the possibility of such
# damage or existence of a defect, except proven that it results out
# of said person’s immediate fault when using the work as intended.

function die {
	print -ru2 -- "E: $*"
	exit 1
}

cc= cf= dc= df=
nt=true
while [[ $1 = -* ]]; do
	case $1 {
	(-cc)	cc=$2; shift ;;
	(-cf)	cf=$2; shift ;;
	(-dc)	dc=$2; shift ;;
	(-df)	df=$2; shift ;;
	(-t)	nt=false ;;
	(*)	die "usage: $0 [-{c,d}c 'gzip -n9'] [-cf control.tar.gz] [-df data.tar.gz] [-t]" ;;
	}
	shift
done
hasc=true hasd=true
[[ -n $cc && -n $cf ]] || hasc=false
[[ -n $dc && -n $df ]] || hasd=false

function chkdir {
	local i x

	[[ -s debian-binary ]] || return 1
	[[ $(<debian-binary) = 2.0 ]] || return 1
	[[ -d c && -d d ]] || return 1
	$hasc || {
		i=0; for x in control.*; do
			[[ $x = *.tar@(|.gz|.xz|.zst) ]] || return 1
			let i++
		done
		(( i == 1 )) || return 1
	}
	$hasd || {
		i=0; for x in data.*; do
			[[ $x = *.tar@(|.bz2|.gz|.xz|.zst) ]] || return 1
			let i++
		done
		(( i == 1 )) || return 1
	}
	[[ -s c/control ]]
}

while ! chkdir; do
	[[ $(realpath .) = +(/) ]] && die cannot find top-level dir
	cd ..
done

$hasc || for cf in control.*; do
	case $cf {
	(*.tar) cc=cat ;;
	(*.tar.gz) cc='gzip -n9' ;;
	(*.tar.xz) cc='xz -2' ;;
	(*.tar.bz*|*.tar.zst)
		print -ru2 -- "W: unsupported format, using gzip for control tarball"
		mv "$cf" control.tar.gz
		cf=control.tar.gz
		cc='gzip -n9' ;;
	(*) die "huh? control.* = $cf" ;;
	}
	break
done
$hasd || for df in data.*; do
	case $df {
	(*.tar) dc=cat ;;
	(*.tar.bz2) dc='bzip2' ;;
	(*.tar.gz) dc='gzip -n9' ;;
	(*.tar.xz) dc='xz' ;;
	(*.tar.bz*|*.tar.zst)
		print -ru2 -- "W: unsupported format, using xz for data tarball"
		mv "$df" data.tar.xz
		df=data.tar.xz
		dc='xz' ;;
	(*) die "huh? data.* = $df" ;;
	}
	break
done

fp=$(sed -n '/^Package: /s///p' c/control)
fv=$(sed -n '/^Version: /s///p' c/control)
fa=$(sed -n '/^Architecture: /s///p' c/control)
fA=$(sed -n '/^Architecture-Variant: /s///p' c/control)
[[ $fp = +([a-zA-Z0-9.+~:-]) ]] || die "huh? fp $fp"
[[ $fv = +([a-zA-Z0-9.+~:-]) ]] || die "huh? fv $fv"
[[ $fa = +([a-zA-Z0-9.+~:-]) ]] || die "huh? fa $fa"
if [[ -n $fA ]]; then
	[[ $fA = +([a-zA-Z0-9.+~:-]) ]] || die "huh? fA $fA"
	[[ $fA = "$fa"?* ]] || die "fA $fA mismatch fa $fa"
	fa=$fA
fi

rm -f debrepack.tmp*
function touchif {
	if [[ -e $1 ]]; then
		touch -r "$1" "debrepack.tmp.${1//'/'/}"
	fi
}
function retouch {
	if [[ -e debrepack.tmp.${1//'/'/} ]]; then
		touch -r "debrepack.tmp.${1//'/'/}" "$1"
	fi
}

set -o pipefail
set -e

# calculate installed-size exactly like dpkg-gencontrol does
# (though it’s still lower, by 1 at least, due to metadata)
is=$(find d -printf '%D:%i %s %y\n' | sort | {
	typeset -Uui is=0
	lasti=
	while read -r i s t; do
		if [[ $t != [fl] ]]; then
			((# ++is ))
			continue
		fi
		[[ $i != "$lasti" ]] || continue
		((# is += (s + 1023) / 1024 ))
		lasti=$i
	done
	print $is
})

set -x

if $nt; then
	touchif "$cf"
	touchif "$df"
fi

if [[ $is = [1-9]*([0-9]) ]]; then
	touchif c/control
	perl -pi -e "s/^installed-size:.*\$/Installed-Size: $is/i" c/control
	retouch c/control
fi

touchif c/md5sums
(cd d && find . -type f -print0 | \
    sed -z s,^./,, | \
    sort -z | \
    xargs -0 md5sum --) >c/md5sums
retouch c/md5sums
(cd d && find . -print0 | \
    sort -z | \
    paxcpio -oC512 -0 -Hustar -Minodes -Mlinks -Muidgid -Mgslash) | \
    eval "$dc" >"$df"
retouch "$df"
find c -type f -print0 | xargs -0 chmod 644 --
for x in c/config c/@(post|pre)@(inst|rm); do
	[[ ! -h $x && -f $x ]] || continue
	chmod 755 "$x"
done
(cd c && find . -print0 | \
    sort -z | \
    paxcpio -oC512 -0 -Hustar -Minodes -Mlinks -Muidgid -Mgslash) | \
    eval "$cc" >"$cf"
retouch "$cf"
$nt || touch debian-binary
paxtar -D ar -M dist -cf "${fp}_${fv}_${fa}.deb" debian-binary "$cf" "$df"
rm -f debrepack.tmp*
