#!/bin/mksh
# $MirOS: contrib/hosted/tg/deb/dscls,v 1.1 2014/04/07 20:31:31 tg Exp $
#-
# Copyright © 2012
#	Thorsten Glaser <tg@mirbsd.org>
#
# Provided that these terms and disclaimer and all copyright notices
# are retained or reproduced in an accompanying document, permission
# is granted to deal in this work without restriction, including un‐
# limited rights to use, publicly perform, distribute, sell, modify,
# merge, give away, or sublicence.
#
# This work is provided “AS IS” and WITHOUT WARRANTY of any kind, to
# the utmost extent permitted by applicable law, neither express nor
# implied; without malicious intent or gross negligence. In no event
# may a licensor, author or contributor be held liable for indirect,
# direct, other damage, loss, or other issues arising in any way out
# of dealing in the work, even if advised of the possibility of such
# damage or existence of a defect, except proven that it results out
# of said person’s immediate fault when using the work as intended.

for x in "$@"; do
	dscname=$x
	pkgname=${x%%@(.dsc|_+([a-z0-9-]).changes)}
	if [[ -s $dscname ]]; then
		y=$(sed -n '/^Source: /s///p' "$dscname" | head -n 1)
		z=$(sed -n '/^Version: /s///p' "$dscname" | head -n 1)
		[[ -n $y && -n $z && $x = ?(*/)${y}_* ]] && pkgname=${y}_$z
	fi
	print -r -- "$pkgname"
done
